### ISSUE TITLE
Problem while doing catkin build; "No package `ocs2_legged_robot`"

### ISSUE THREAD

**Issue by syw-robotics** [bridgedp/hunter_bipedal_control#9]
Thanks so much for making this work open-sourced!

I was following the installation guide, and during catkin build, it showed no `ocs2_legged_robot` pkg was found;

I am new to ocs2 and did not compile the entire ocs2 repo because it's massive, meanwhile I failed to find `ocs2_legged_robot` in the ocs2 repo.

Here is the error report:
![image](https://github.com/bridgedp/hunter_bipedal_control/assets/84261527/953ba157-f943-4613-969e-fbf427b12880)

I'll be so much appreciated if there is a reply. ^v^

**Comment by syw-robotics** [comment]
problem resolved

**Comment by rcone11** [comment]
> problem resolved

你好，我遇到了和你相同的问题，请问你是如何解决的

**Comment by syw-robotics** [comment]
> > problem resolved
> 
> 你好，我遇到了和你相同的问题，请问你是如何解决的

仓库是参考legged_control构建的，可以看看legged_control的readme，先`catkin build ocs2_legged_robot_ros ocs2_self_collision_visualization`
